# Generated by Django 3.1 on 2020-09-11 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=False,
                        help_text="Статус выполнения задания",
                        verbose_name="Статус задания",
                    ),
                ),
                (
                    "assessment",
                    models.BooleanField(
                        blank=True,
                        help_text="Оценка правильности выполнения задания",
                        null=True,
                        verbose_name="Оценка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Пользователь, выполняющий задание",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translate_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word",
                    models.CharField(
                        help_text="Слово для перевода",
                        max_length=20,
                        verbose_name="Слово для перевода",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Задание, содержащее слово",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="translate_app.task",
                        verbose_name="Задание",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnswerOptions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.CharField(max_length=20)),
                ("bait_1", models.CharField(max_length=20)),
                ("bait_2", models.CharField(max_length=20)),
                ("bait_3", models.CharField(max_length=20)),
                (
                    "question",
                    models.ForeignKey(
                        help_text="Варианты ответа на вопрос",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="translate_app.question",
                        verbose_name="Варианты ответа",
                    ),
                ),
            ],
        ),
    ]
