# Generated by Django 3.1 on 2020-09-12 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_auto_20200819_1925'),
        ('translate_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroptions',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='translations.word'),
        ),
        migrations.AlterField(
            model_name='answeroptions',
            name='bait_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='translations.word'),
        ),
        migrations.AlterField(
            model_name='answeroptions',
            name='bait_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='translations.word'),
        ),
        migrations.AlterField(
            model_name='answeroptions',
            name='bait_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='translations.word'),
        ),
    ]
