# Generated by Django 3.1 on 2020-09-17 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translate_app', '0003_auto_20200912_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='assessment',
            field=models.BooleanField(blank=True, help_text='Оценка правильности ответа на вопрос', null=True, verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.BooleanField(default=False, help_text='Статус ответа на вопрос', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='answeroptions',
            name='question',
            field=models.OneToOneField(help_text='Варианты ответа на вопрос', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='translate_app.question', verbose_name='Варианты ответа'),
        ),
    ]
