# Generated by Django 3.1 on 2020-08-10 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('lang', models.CharField(choices=[('EN', 'En'), ('RU', 'Ru'), ('NO', 'No')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('source_word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='translations.word')),
                ('target_word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='translations.word')),
            ],
        ),
    ]
