# Generated by Django 3.1 on 2020-09-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_auto_20200819_1925'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='translation',
            constraint=models.UniqueConstraint(fields=('source_word', 'target_word'), name='No duplicate translations'),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('word', 'lang'), name='One word per language'),
        ),
    ]
