# Generated by Django 3.1 on 2020-08-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallows", "0002_auto_20200815_0754"),
    ]

    operations = [
        migrations.RemoveField(model_name="game", name="id",),
        migrations.AddField(
            model_name="game",
            name="game_id",
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
