# Generated by Django 3.1 on 2020-08-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallows", "0003_auto_20200815_0855"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="game_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
