# Generated by Django 3.1 on 2020-08-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallows', '0004_auto_20200815_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='current_guess',
        ),
        migrations.RemoveField(
            model_name='game',
            name='difficulty',
        ),
    ]
