# Generated by Django 3.1 on 2020-08-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallows", "0008_remove_game_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="language",
            field=models.CharField(default="en", max_length=2),
            preserve_default=False,
        ),
    ]
